// Complete 8085 Instruction Set
const INSTRUCTIONS = [
    // Data Transfer Instructions
    { mnemonic: "MOV r1, r2", opcode: "Various", bytes: 1, category: "data-transfer", description: "Move data from register r2 to r1" },
    { mnemonic: "MOV A, B", opcode: "78", bytes: 1, category: "data-transfer", description: "Move B to A" },
    { mnemonic: "MOV A, C", opcode: "79", bytes: 1, category: "data-transfer", description: "Move C to A" },
    { mnemonic: "MOV A, D", opcode: "7A", bytes: 1, category: "data-transfer", description: "Move D to A" },
    { mnemonic: "MOV A, E", opcode: "7B", bytes: 1, category: "data-transfer", description: "Move E to A" },
    { mnemonic: "MOV A, H", opcode: "7C", bytes: 1, category: "data-transfer", description: "Move H to A" },
    { mnemonic: "MOV A, L", opcode: "7D", bytes: 1, category: "data-transfer", description: "Move L to A" },
    { mnemonic: "MOV A, M", opcode: "7E", bytes: 1, category: "data-transfer", description: "Move memory to A" },
    { mnemonic: "MOV B, A", opcode: "47", bytes: 1, category: "data-transfer", description: "Move A to B" },
    { mnemonic: "MOV B, C", opcode: "41", bytes: 1, category: "data-transfer", description: "Move C to B" },
    { mnemonic: "MOV B, D", opcode: "42", bytes: 1, category: "data-transfer", description: "Move D to B" },
    { mnemonic: "MOV B, E", opcode: "43", bytes: 1, category: "data-transfer", description: "Move E to B" },
    { mnemonic: "MOV B, H", opcode: "44", bytes: 1, category: "data-transfer", description: "Move H to B" },
    { mnemonic: "MOV B, L", opcode: "45", bytes: 1, category: "data-transfer", description: "Move L to B" },
    { mnemonic: "MOV B, M", opcode: "46", bytes: 1, category: "data-transfer", description: "Move memory to B" },
    { mnemonic: "MOV C, A", opcode: "4F", bytes: 1, category: "data-transfer", description: "Move A to C" },
    { mnemonic: "MOV C, B", opcode: "48", bytes: 1, category: "data-transfer", description: "Move B to C" },
    { mnemonic: "MOV C, D", opcode: "4A", bytes: 1, category: "data-transfer", description: "Move D to C" },
    { mnemonic: "MOV C, E", opcode: "4B", bytes: 1, category: "data-transfer", description: "Move E to C" },
    { mnemonic: "MOV C, H", opcode: "4C", bytes: 1, category: "data-transfer", description: "Move H to C" },
    { mnemonic: "MOV C, L", opcode: "4D", bytes: 1, category: "data-transfer", description: "Move L to C" },
    { mnemonic: "MOV C, M", opcode: "4E", bytes: 1, category: "data-transfer", description: "Move memory to C" },
    { mnemonic: "MOV D, A", opcode: "57", bytes: 1, category: "data-transfer", description: "Move A to D" },
    { mnemonic: "MOV D, B", opcode: "50", bytes: 1, category: "data-transfer", description: "Move B to D" },
    { mnemonic: "MOV D, C", opcode: "51", bytes: 1, category: "data-transfer", description: "Move C to D" },
    { mnemonic: "MOV D, E", opcode: "53", bytes: 1, category: "data-transfer", description: "Move E to D" },
    { mnemonic: "MOV D, H", opcode: "54", bytes: 1, category: "data-transfer", description: "Move H to D" },
    { mnemonic: "MOV D, L", opcode: "55", bytes: 1, category: "data-transfer", description: "Move L to D" },
    { mnemonic: "MOV D, M", opcode: "56", bytes: 1, category: "data-transfer", description: "Move memory to D" },
    { mnemonic: "MOV E, A", opcode: "5F", bytes: 1, category: "data-transfer", description: "Move A to E" },
    { mnemonic: "MOV E, B", opcode: "58", bytes: 1, category: "data-transfer", description: "Move B to E" },
    { mnemonic: "MOV E, C", opcode: "59", bytes: 1, category: "data-transfer", description: "Move C to E" },
    { mnemonic: "MOV E, D", opcode: "5A", bytes: 1, category: "data-transfer", description: "Move D to E" },
    { mnemonic: "MOV E, H", opcode: "5C", bytes: 1, category: "data-transfer", description: "Move H to E" },
    { mnemonic: "MOV E, L", opcode: "5D", bytes: 1, category: "data-transfer", description: "Move L to E" },
    { mnemonic: "MOV E, M", opcode: "5E", bytes: 1, category: "data-transfer", description: "Move memory to E" },
    { mnemonic: "MOV H, A", opcode: "67", bytes: 1, category: "data-transfer", description: "Move A to H" },
    { mnemonic: "MOV H, B", opcode: "60", bytes: 1, category: "data-transfer", description: "Move B to H" },
    { mnemonic: "MOV H, C", opcode: "61", bytes: 1, category: "data-transfer", description: "Move C to H" },
    { mnemonic: "MOV H, D", opcode: "62", bytes: 1, category: "data-transfer", description: "Move D to H" },
    { mnemonic: "MOV H, E", opcode: "63", bytes: 1, category: "data-transfer", description: "Move E to H" },
    { mnemonic: "MOV H, L", opcode: "65", bytes: 1, category: "data-transfer", description: "Move L to H" },
    { mnemonic: "MOV H, M", opcode: "66", bytes: 1, category: "data-transfer", description: "Move memory to H" },
    { mnemonic: "MOV L, A", opcode: "6F", bytes: 1, category: "data-transfer", description: "Move A to L" },
    { mnemonic: "MOV L, B", opcode: "68", bytes: 1, category: "data-transfer", description: "Move B to L" },
    { mnemonic: "MOV L, C", opcode: "69", bytes: 1, category: "data-transfer", description: "Move C to L" },
    { mnemonic: "MOV L, D", opcode: "6A", bytes: 1, category: "data-transfer", description: "Move D to L" },
    { mnemonic: "MOV L, E", opcode: "6B", bytes: 1, category: "data-transfer", description: "Move E to L" },
    { mnemonic: "MOV L, H", opcode: "6C", bytes: 1, category: "data-transfer", description: "Move H to L" },
    { mnemonic: "MOV L, M", opcode: "6E", bytes: 1, category: "data-transfer", description: "Move memory to L" },
    { mnemonic: "MOV M, A", opcode: "77", bytes: 1, category: "data-transfer", description: "Move A to memory" },
    { mnemonic: "MOV M, B", opcode: "70", bytes: 1, category: "data-transfer", description: "Move B to memory" },
    { mnemonic: "MOV M, C", opcode: "71", bytes: 1, category: "data-transfer", description: "Move C to memory" },
    { mnemonic: "MOV M, D", opcode: "72", bytes: 1, category: "data-transfer", description: "Move D to memory" },
    { mnemonic: "MOV M, E", opcode: "73", bytes: 1, category: "data-transfer", description: "Move E to memory" },
    { mnemonic: "MOV M, H", opcode: "74", bytes: 1, category: "data-transfer", description: "Move H to memory" },
    { mnemonic: "MOV M, L", opcode: "75", bytes: 1, category: "data-transfer", description: "Move L to memory" },
    { mnemonic: "MVI A, data", opcode: "3E", bytes: 2, category: "data-transfer", description: "Move immediate to A" },
    { mnemonic: "MVI B, data", opcode: "06", bytes: 2, category: "data-transfer", description: "Move immediate to B" },
    { mnemonic: "MVI C, data", opcode: "0E", bytes: 2, category: "data-transfer", description: "Move immediate to C" },
    { mnemonic: "MVI D, data", opcode: "16", bytes: 2, category: "data-transfer", description: "Move immediate to D" },
    { mnemonic: "MVI E, data", opcode: "1E", bytes: 2, category: "data-transfer", description: "Move immediate to E" },
    { mnemonic: "MVI H, data", opcode: "26", bytes: 2, category: "data-transfer", description: "Move immediate to H" },
    { mnemonic: "MVI L, data", opcode: "2E", bytes: 2, category: "data-transfer", description: "Move immediate to L" },
    { mnemonic: "MVI M, data", opcode: "36", bytes: 2, category: "data-transfer", description: "Move immediate to memory" },
    { mnemonic: "LXI B, data16", opcode: "01", bytes: 3, category: "data-transfer", description: "Load immediate BC pair" },
    { mnemonic: "LXI D, data16", opcode: "11", bytes: 3, category: "data-transfer", description: "Load immediate DE pair" },
    { mnemonic: "LXI H, data16", opcode: "21", bytes: 3, category: "data-transfer", description: "Load immediate HL pair" },
    { mnemonic: "LXI SP, data16", opcode: "31", bytes: 3, category: "data-transfer", description: "Load immediate SP" },
    { mnemonic: "LDA addr", opcode: "3A", bytes: 3, category: "data-transfer", description: "Load A from address" },
    { mnemonic: "STA addr", opcode: "32", bytes: 3, category: "data-transfer", description: "Store A to address" },
    { mnemonic: "LHLD addr", opcode: "2A", bytes: 3, category: "data-transfer", description: "Load HL from address" },
    { mnemonic: "SHLD addr", opcode: "22", bytes: 3, category: "data-transfer", description: "Store HL to address" },
    { mnemonic: "LDAX B", opcode: "0A", bytes: 1, category: "data-transfer", description: "Load A indirect from BC" },
    { mnemonic: "LDAX D", opcode: "1A", bytes: 1, category: "data-transfer", description: "Load A indirect from DE" },
    { mnemonic: "STAX B", opcode: "02", bytes: 1, category: "data-transfer", description: "Store A indirect to BC" },
    { mnemonic: "STAX D", opcode: "12", bytes: 1, category: "data-transfer", description: "Store A indirect to DE" },
    { mnemonic: "XCHG", opcode: "EB", bytes: 1, category: "data-transfer", description: "Exchange HL with DE" },

    // Arithmetic Instructions
    { mnemonic: "ADD A", opcode: "87", bytes: 1, category: "arithmetic", description: "Add A to A" },
    { mnemonic: "ADD B", opcode: "80", bytes: 1, category: "arithmetic", description: "Add B to A" },
    { mnemonic: "ADD C", opcode: "81", bytes: 1, category: "arithmetic", description: "Add C to A" },
    { mnemonic: "ADD D", opcode: "82", bytes: 1, category: "arithmetic", description: "Add D to A" },
    { mnemonic: "ADD E", opcode: "83", bytes: 1, category: "arithmetic", description: "Add E to A" },
    { mnemonic: "ADD H", opcode: "84", bytes: 1, category: "arithmetic", description: "Add H to A" },
    { mnemonic: "ADD L", opcode: "85", bytes: 1, category: "arithmetic", description: "Add L to A" },
    { mnemonic: "ADD M", opcode: "86", bytes: 1, category: "arithmetic", description: "Add memory to A" },
    { mnemonic: "ADI data", opcode: "C6", bytes: 2, category: "arithmetic", description: "Add immediate to A" },
    { mnemonic: "ADC A", opcode: "8F", bytes: 1, category: "arithmetic", description: "Add A with carry to A" },
    { mnemonic: "ADC B", opcode: "88", bytes: 1, category: "arithmetic", description: "Add B with carry to A" },
    { mnemonic: "ADC C", opcode: "89", bytes: 1, category: "arithmetic", description: "Add C with carry to A" },
    { mnemonic: "ADC D", opcode: "8A", bytes: 1, category: "arithmetic", description: "Add D with carry to A" },
    { mnemonic: "ADC E", opcode: "8B", bytes: 1, category: "arithmetic", description: "Add E with carry to A" },
    { mnemonic: "ADC H", opcode: "8C", bytes: 1, category: "arithmetic", description: "Add H with carry to A" },
    { mnemonic: "ADC L", opcode: "8D", bytes: 1, category: "arithmetic", description: "Add L with carry to A" },
    { mnemonic: "ADC M", opcode: "8E", bytes: 1, category: "arithmetic", description: "Add memory with carry to A" },
    { mnemonic: "ACI data", opcode: "CE", bytes: 2, category: "arithmetic", description: "Add immediate with carry to A" },
    { mnemonic: "SUB A", opcode: "97", bytes: 1, category: "arithmetic", description: "Subtract A from A" },
    { mnemonic: "SUB B", opcode: "90", bytes: 1, category: "arithmetic", description: "Subtract B from A" },
    { mnemonic: "SUB C", opcode: "91", bytes: 1, category: "arithmetic", description: "Subtract C from A" },
    { mnemonic: "SUB D", opcode: "92", bytes: 1, category: "arithmetic", description: "Subtract D from A" },
    { mnemonic: "SUB E", opcode: "93", bytes: 1, category: "arithmetic", description: "Subtract E from A" },
    { mnemonic: "SUB H", opcode: "94", bytes: 1, category: "arithmetic", description: "Subtract H from A" },
    { mnemonic: "SUB L", opcode: "95", bytes: 1, category: "arithmetic", description: "Subtract L from A" },
    { mnemonic: "SUB M", opcode: "96", bytes: 1, category: "arithmetic", description: "Subtract memory from A" },
    { mnemonic: "SUI data", opcode: "D6", bytes: 2, category: "arithmetic", description: "Subtract immediate from A" },
    { mnemonic: "SBB A", opcode: "9F", bytes: 1, category: "arithmetic", description: "Subtract A with borrow" },
    { mnemonic: "SBB B", opcode: "98", bytes: 1, category: "arithmetic", description: "Subtract B with borrow" },
    { mnemonic: "SBB C", opcode: "99", bytes: 1, category: "arithmetic", description: "Subtract C with borrow" },
    { mnemonic: "SBB D", opcode: "9A", bytes: 1, category: "arithmetic", description: "Subtract D with borrow" },
    { mnemonic: "SBB E", opcode: "9B", bytes: 1, category: "arithmetic", description: "Subtract E with borrow" },
    { mnemonic: "SBB H", opcode: "9C", bytes: 1, category: "arithmetic", description: "Subtract H with borrow" },
    { mnemonic: "SBB L", opcode: "9D", bytes: 1, category: "arithmetic", description: "Subtract L with borrow" },
    { mnemonic: "SBB M", opcode: "9E", bytes: 1, category: "arithmetic", description: "Subtract memory with borrow" },
    { mnemonic: "SBI data", opcode: "DE", bytes: 2, category: "arithmetic", description: "Subtract immediate with borrow" },
    { mnemonic: "INR A", opcode: "3C", bytes: 1, category: "arithmetic", description: "Increment A" },
    { mnemonic: "INR B", opcode: "04", bytes: 1, category: "arithmetic", description: "Increment B" },
    { mnemonic: "INR C", opcode: "0C", bytes: 1, category: "arithmetic", description: "Increment C" },
    { mnemonic: "INR D", opcode: "14", bytes: 1, category: "arithmetic", description: "Increment D" },
    { mnemonic: "INR E", opcode: "1C", bytes: 1, category: "arithmetic", description: "Increment E" },
    { mnemonic: "INR H", opcode: "24", bytes: 1, category: "arithmetic", description: "Increment H" },
    { mnemonic: "INR L", opcode: "2C", bytes: 1, category: "arithmetic", description: "Increment L" },
    { mnemonic: "INR M", opcode: "34", bytes: 1, category: "arithmetic", description: "Increment memory" },
    { mnemonic: "DCR A", opcode: "3D", bytes: 1, category: "arithmetic", description: "Decrement A" },
    { mnemonic: "DCR B", opcode: "05", bytes: 1, category: "arithmetic", description: "Decrement B" },
    { mnemonic: "DCR C", opcode: "0D", bytes: 1, category: "arithmetic", description: "Decrement C" },
    { mnemonic: "DCR D", opcode: "15", bytes: 1, category: "arithmetic", description: "Decrement D" },
    { mnemonic: "DCR E", opcode: "1D", bytes: 1, category: "arithmetic", description: "Decrement E" },
    { mnemonic: "DCR H", opcode: "25", bytes: 1, category: "arithmetic", description: "Decrement H" },
    { mnemonic: "DCR L", opcode: "2D", bytes: 1, category: "arithmetic", description: "Decrement L" },
    { mnemonic: "DCR M", opcode: "35", bytes: 1, category: "arithmetic", description: "Decrement memory" },
    { mnemonic: "INX B", opcode: "03", bytes: 1, category: "arithmetic", description: "Increment BC pair" },
    { mnemonic: "INX D", opcode: "13", bytes: 1, category: "arithmetic", description: "Increment DE pair" },
    { mnemonic: "INX H", opcode: "23", bytes: 1, category: "arithmetic", description: "Increment HL pair" },
    { mnemonic: "INX SP", opcode: "33", bytes: 1, category: "arithmetic", description: "Increment SP" },
    { mnemonic: "DCX B", opcode: "0B", bytes: 1, category: "arithmetic", description: "Decrement BC pair" },
    { mnemonic: "DCX D", opcode: "1B", bytes: 1, category: "arithmetic", description: "Decrement DE pair" },
    { mnemonic: "DCX H", opcode: "2B", bytes: 1, category: "arithmetic", description: "Decrement HL pair" },
    { mnemonic: "DCX SP", opcode: "3B", bytes: 1, category: "arithmetic", description: "Decrement SP" },
    { mnemonic: "DAD B", opcode: "09", bytes: 1, category: "arithmetic", description: "Add BC to HL" },
    { mnemonic: "DAD D", opcode: "19", bytes: 1, category: "arithmetic", description: "Add DE to HL" },
    { mnemonic: "DAD H", opcode: "29", bytes: 1, category: "arithmetic", description: "Add HL to HL" },
    { mnemonic: "DAD SP", opcode: "39", bytes: 1, category: "arithmetic", description: "Add SP to HL" },
    { mnemonic: "DAA", opcode: "27", bytes: 1, category: "arithmetic", description: "Decimal adjust accumulator" },

    // Logical Instructions
    { mnemonic: "ANA A", opcode: "A7", bytes: 1, category: "logical", description: "AND A with A" },
    { mnemonic: "ANA B", opcode: "A0", bytes: 1, category: "logical", description: "AND B with A" },
    { mnemonic: "ANA C", opcode: "A1", bytes: 1, category: "logical", description: "AND C with A" },
    { mnemonic: "ANA D", opcode: "A2", bytes: 1, category: "logical", description: "AND D with A" },
    { mnemonic: "ANA E", opcode: "A3", bytes: 1, category: "logical", description: "AND E with A" },
    { mnemonic: "ANA H", opcode: "A4", bytes: 1, category: "logical", description: "AND H with A" },
    { mnemonic: "ANA L", opcode: "A5", bytes: 1, category: "logical", description: "AND L with A" },
    { mnemonic: "ANA M", opcode: "A6", bytes: 1, category: "logical", description: "AND memory with A" },
    { mnemonic: "ANI data", opcode: "E6", bytes: 2, category: "logical", description: "AND immediate with A" },
    { mnemonic: "ORA A", opcode: "B7", bytes: 1, category: "logical", description: "OR A with A" },
    { mnemonic: "ORA B", opcode: "B0", bytes: 1, category: "logical", description: "OR B with A" },
    { mnemonic: "ORA C", opcode: "B1", bytes: 1, category: "logical", description: "OR C with A" },
    { mnemonic: "ORA D", opcode: "B2", bytes: 1, category: "logical", description: "OR D with A" },
    { mnemonic: "ORA E", opcode: "B3", bytes: 1, category: "logical", description: "OR E with A" },
    { mnemonic: "ORA H", opcode: "B4", bytes: 1, category: "logical", description: "OR H with A" },
    { mnemonic: "ORA L", opcode: "B5", bytes: 1, category: "logical", description: "OR L with A" },
    { mnemonic: "ORA M", opcode: "B6", bytes: 1, category: "logical", description: "OR memory with A" },
    { mnemonic: "ORI data", opcode: "F6", bytes: 2, category: "logical", description: "OR immediate with A" },
    { mnemonic: "XRA A", opcode: "AF", bytes: 1, category: "logical", description: "XOR A with A" },
    { mnemonic: "XRA B", opcode: "A8", bytes: 1, category: "logical", description: "XOR B with A" },
    { mnemonic: "XRA C", opcode: "A9", bytes: 1, category: "logical", description: "XOR C with A" },
    { mnemonic: "XRA D", opcode: "AA", bytes: 1, category: "logical", description: "XOR D with A" },
    { mnemonic: "XRA E", opcode: "AB", bytes: 1, category: "logical", description: "XOR E with A" },
    { mnemonic: "XRA H", opcode: "AC", bytes: 1, category: "logical", description: "XOR H with A" },
    { mnemonic: "XRA L", opcode: "AD", bytes: 1, category: "logical", description: "XOR L with A" },
    { mnemonic: "XRA M", opcode: "AE", bytes: 1, category: "logical", description: "XOR memory with A" },
    { mnemonic: "XRI data", opcode: "EE", bytes: 2, category: "logical", description: "XOR immediate with A" },
    { mnemonic: "CMP A", opcode: "BF", bytes: 1, category: "logical", description: "Compare A with A" },
    { mnemonic: "CMP B", opcode: "B8", bytes: 1, category: "logical", description: "Compare B with A" },
    { mnemonic: "CMP C", opcode: "B9", bytes: 1, category: "logical", description: "Compare C with A" },
    { mnemonic: "CMP D", opcode: "BA", bytes: 1, category: "logical", description: "Compare D with A" },
    { mnemonic: "CMP E", opcode: "BB", bytes: 1, category: "logical", description: "Compare E with A" },
    { mnemonic: "CMP H", opcode: "BC", bytes: 1, category: "logical", description: "Compare H with A" },
    { mnemonic: "CMP L", opcode: "BD", bytes: 1, category: "logical", description: "Compare L with A" },
    { mnemonic: "CMP M", opcode: "BE", bytes: 1, category: "logical", description: "Compare memory with A" },
    { mnemonic: "CPI data", opcode: "FE", bytes: 2, category: "logical", description: "Compare immediate with A" },
    { mnemonic: "RLC", opcode: "07", bytes: 1, category: "logical", description: "Rotate A left" },
    { mnemonic: "RRC", opcode: "0F", bytes: 1, category: "logical", description: "Rotate A right" },
    { mnemonic: "RAL", opcode: "17", bytes: 1, category: "logical", description: "Rotate A left through carry" },
    { mnemonic: "RAR", opcode: "1F", bytes: 1, category: "logical", description: "Rotate A right through carry" },
    { mnemonic: "CMA", opcode: "2F", bytes: 1, category: "logical", description: "Complement A" },
    { mnemonic: "CMC", opcode: "3F", bytes: 1, category: "logical", description: "Complement carry flag" },
    { mnemonic: "STC", opcode: "37", bytes: 1, category: "logical", description: "Set carry flag" },

    // Branch Instructions
    { mnemonic: "JMP addr", opcode: "C3", bytes: 3, category: "branch", description: "Jump unconditionally" },
    { mnemonic: "JC addr", opcode: "DA", bytes: 3, category: "branch", description: "Jump if carry" },
    { mnemonic: "JNC addr", opcode: "D2", bytes: 3, category: "branch", description: "Jump if no carry" },
    { mnemonic: "JZ addr", opcode: "CA", bytes: 3, category: "branch", description: "Jump if zero" },
    { mnemonic: "JNZ addr", opcode: "C2", bytes: 3, category: "branch", description: "Jump if not zero" },
    { mnemonic: "JP addr", opcode: "F2", bytes: 3, category: "branch", description: "Jump if positive" },
    { mnemonic: "JM addr", opcode: "FA", bytes: 3, category: "branch", description: "Jump if minus" },
    { mnemonic: "JPE addr", opcode: "EA", bytes: 3, category: "branch", description: "Jump if parity even" },
    { mnemonic: "JPO addr", opcode: "E2", bytes: 3, category: "branch", description: "Jump if parity odd" },
    { mnemonic: "CALL addr", opcode: "CD", bytes: 3, category: "branch", description: "Call subroutine" },
    { mnemonic: "CC addr", opcode: "DC", bytes: 3, category: "branch", description: "Call if carry" },
    { mnemonic: "CNC addr", opcode: "D4", bytes: 3, category: "branch", description: "Call if no carry" },
    { mnemonic: "CZ addr", opcode: "CC", bytes: 3, category: "branch", description: "Call if zero" },
    { mnemonic: "CNZ addr", opcode: "C4", bytes: 3, category: "branch", description: "Call if not zero" },
    { mnemonic: "CP addr", opcode: "F4", bytes: 3, category: "branch", description: "Call if positive" },
    { mnemonic: "CM addr", opcode: "FC", bytes: 3, category: "branch", description: "Call if minus" },
    { mnemonic: "CPE addr", opcode: "EC", bytes: 3, category: "branch", description: "Call if parity even" },
    { mnemonic: "CPO addr", opcode: "E4", bytes: 3, category: "branch", description: "Call if parity odd" },
    { mnemonic: "RET", opcode: "C9", bytes: 1, category: "branch", description: "Return from subroutine" },
    { mnemonic: "RC", opcode: "D8", bytes: 1, category: "branch", description: "Return if carry" },
    { mnemonic: "RNC", opcode: "D0", bytes: 1, category: "branch", description: "Return if no carry" },
    { mnemonic: "RZ", opcode: "C8", bytes: 1, category: "branch", description: "Return if zero" },
    { mnemonic: "RNZ", opcode: "C0", bytes: 1, category: "branch", description: "Return if not zero" },
    { mnemonic: "RP", opcode: "F0", bytes: 1, category: "branch", description: "Return if positive" },
    { mnemonic: "RM", opcode: "F8", bytes: 1, category: "branch", description: "Return if minus" },
    { mnemonic: "RPE", opcode: "E8", bytes: 1, category: "branch", description: "Return if parity even" },
    { mnemonic: "RPO", opcode: "E0", bytes: 1, category: "branch", description: "Return if parity odd" },
    { mnemonic: "PCHL", opcode: "E9", bytes: 1, category: "branch", description: "Jump to address in HL" },
    { mnemonic: "RST 0", opcode: "C7", bytes: 1, category: "branch", description: "Restart at 0000H" },
    { mnemonic: "RST 1", opcode: "CF", bytes: 1, category: "branch", description: "Restart at 0008H" },
    { mnemonic: "RST 2", opcode: "D7", bytes: 1, category: "branch", description: "Restart at 0010H" },
    { mnemonic: "RST 3", opcode: "DF", bytes: 1, category: "branch", description: "Restart at 0018H" },
    { mnemonic: "RST 4", opcode: "E7", bytes: 1, category: "branch", description: "Restart at 0020H" },
    { mnemonic: "RST 5", opcode: "EF", bytes: 1, category: "branch", description: "Restart at 0028H" },
    { mnemonic: "RST 6", opcode: "F7", bytes: 1, category: "branch", description: "Restart at 0030H" },
    { mnemonic: "RST 7", opcode: "FF", bytes: 1, category: "branch", description: "Restart at 0038H" },

    // Stack Instructions
    { mnemonic: "PUSH B", opcode: "C5", bytes: 1, category: "stack", description: "Push BC to stack" },
    { mnemonic: "PUSH D", opcode: "D5", bytes: 1, category: "stack", description: "Push DE to stack" },
    { mnemonic: "PUSH H", opcode: "E5", bytes: 1, category: "stack", description: "Push HL to stack" },
    { mnemonic: "PUSH PSW", opcode: "F5", bytes: 1, category: "stack", description: "Push A and flags to stack" },
    { mnemonic: "POP B", opcode: "C1", bytes: 1, category: "stack", description: "Pop BC from stack" },
    { mnemonic: "POP D", opcode: "D1", bytes: 1, category: "stack", description: "Pop DE from stack" },
    { mnemonic: "POP H", opcode: "E1", bytes: 1, category: "stack", description: "Pop HL from stack" },
    { mnemonic: "POP PSW", opcode: "F1", bytes: 1, category: "stack", description: "Pop A and flags from stack" },
    { mnemonic: "XTHL", opcode: "E3", bytes: 1, category: "stack", description: "Exchange HL with top of stack" },
    { mnemonic: "SPHL", opcode: "F9", bytes: 1, category: "stack", description: "Move HL to SP" },

    // I/O Instructions
    { mnemonic: "IN port", opcode: "DB", bytes: 2, category: "io", description: "Input from port to A" },
    { mnemonic: "OUT port", opcode: "D3", bytes: 2, category: "io", description: "Output from A to port" },

    // Control Instructions
    { mnemonic: "NOP", opcode: "00", bytes: 1, category: "control", description: "No operation" },
    { mnemonic: "HLT", opcode: "76", bytes: 1, category: "control", description: "Halt processor" },
    { mnemonic: "DI", opcode: "F3", bytes: 1, category: "control", description: "Disable interrupts" },
    { mnemonic: "EI", opcode: "FB", bytes: 1, category: "control", description: "Enable interrupts" },
    { mnemonic: "RIM", opcode: "20", bytes: 1, category: "control", description: "Read interrupt mask" },
    { mnemonic: "SIM", opcode: "30", bytes: 1, category: "control", description: "Set interrupt mask" }
];

// Opcode lookup table for assembler
const OPCODE_TABLE = {
    // MOV instructions
    "MOV A,A": "7F", "MOV A,B": "78", "MOV A,C": "79", "MOV A,D": "7A",
    "MOV A,E": "7B", "MOV A,H": "7C", "MOV A,L": "7D", "MOV A,M": "7E",
    "MOV B,A": "47", "MOV B,B": "40", "MOV B,C": "41", "MOV B,D": "42",
    "MOV B,E": "43", "MOV B,H": "44", "MOV B,L": "45", "MOV B,M": "46",
    "MOV C,A": "4F", "MOV C,B": "48", "MOV C,C": "49", "MOV C,D": "4A",
    "MOV C,E": "4B", "MOV C,H": "4C", "MOV C,L": "4D", "MOV C,M": "4E",
    "MOV D,A": "57", "MOV D,B": "50", "MOV D,C": "51", "MOV D,D": "52",
    "MOV D,E": "53", "MOV D,H": "54", "MOV D,L": "55", "MOV D,M": "56",
    "MOV E,A": "5F", "MOV E,B": "58", "MOV E,C": "59", "MOV E,D": "5A",
    "MOV E,E": "5B", "MOV E,H": "5C", "MOV E,L": "5D", "MOV E,M": "5E",
    "MOV H,A": "67", "MOV H,B": "60", "MOV H,C": "61", "MOV H,D": "62",
    "MOV H,E": "63", "MOV H,H": "64", "MOV H,L": "65", "MOV H,M": "66",
    "MOV L,A": "6F", "MOV L,B": "68", "MOV L,C": "69", "MOV L,D": "6A",
    "MOV L,E": "6B", "MOV L,H": "6C", "MOV L,L": "6D", "MOV L,M": "6E",
    "MOV M,A": "77", "MOV M,B": "70", "MOV M,C": "71", "MOV M,D": "72",
    "MOV M,E": "73", "MOV M,H": "74", "MOV M,L": "75",

    // MVI instructions
    "MVI A": "3E", "MVI B": "06", "MVI C": "0E", "MVI D": "16",
    "MVI E": "1E", "MVI H": "26", "MVI L": "2E", "MVI M": "36",

    // LXI instructions
    "LXI B": "01", "LXI D": "11", "LXI H": "21", "LXI SP": "31",

    // Load/Store instructions
    "LDA": "3A", "STA": "32", "LHLD": "2A", "SHLD": "22",
    "LDAX B": "0A", "LDAX D": "1A", "STAX B": "02", "STAX D": "12",
    "XCHG": "EB",

    // Arithmetic instructions
    "ADD A": "87", "ADD B": "80", "ADD C": "81", "ADD D": "82",
    "ADD E": "83", "ADD H": "84", "ADD L": "85", "ADD M": "86",
    "ADI": "C6",
    "ADC A": "8F", "ADC B": "88", "ADC C": "89", "ADC D": "8A",
    "ADC E": "8B", "ADC H": "8C", "ADC L": "8D", "ADC M": "8E",
    "ACI": "CE",
    "SUB A": "97", "SUB B": "90", "SUB C": "91", "SUB D": "92",
    "SUB E": "93", "SUB H": "94", "SUB L": "95", "SUB M": "96",
    "SUI": "D6",
    "SBB A": "9F", "SBB B": "98", "SBB C": "99", "SBB D": "9A",
    "SBB E": "9B", "SBB H": "9C", "SBB L": "9D", "SBB M": "9E",
    "SBI": "DE",
    "INR A": "3C", "INR B": "04", "INR C": "0C", "INR D": "14",
    "INR E": "1C", "INR H": "24", "INR L": "2C", "INR M": "34",
    "DCR A": "3D", "DCR B": "05", "DCR C": "0D", "DCR D": "15",
    "DCR E": "1D", "DCR H": "25", "DCR L": "2D", "DCR M": "35",
    "INX B": "03", "INX D": "13", "INX H": "23", "INX SP": "33",
    "DCX B": "0B", "DCX D": "1B", "DCX H": "2B", "DCX SP": "3B",
    "DAD B": "09", "DAD D": "19", "DAD H": "29", "DAD SP": "39",
    "DAA": "27",

    // Logical instructions
    "ANA A": "A7", "ANA B": "A0", "ANA C": "A1", "ANA D": "A2",
    "ANA E": "A3", "ANA H": "A4", "ANA L": "A5", "ANA M": "A6",
    "ANI": "E6",
    "ORA A": "B7", "ORA B": "B0", "ORA C": "B1", "ORA D": "B2",
    "ORA E": "B3", "ORA H": "B4", "ORA L": "B5", "ORA M": "B6",
    "ORI": "F6",
    "XRA A": "AF", "XRA B": "A8", "XRA C": "A9", "XRA D": "AA",
    "XRA E": "AB", "XRA H": "AC", "XRA L": "AD", "XRA M": "AE",
    "XRI": "EE",
    "CMP A": "BF", "CMP B": "B8", "CMP C": "B9", "CMP D": "BA",
    "CMP E": "BB", "CMP H": "BC", "CMP L": "BD", "CMP M": "BE",
    "CPI": "FE",
    "RLC": "07", "RRC": "0F", "RAL": "17", "RAR": "1F",
    "CMA": "2F", "CMC": "3F", "STC": "37",

    // Branch instructions
    "JMP": "C3", "JC": "DA", "JNC": "D2", "JZ": "CA", "JNZ": "C2",
    "JP": "F2", "JM": "FA", "JPE": "EA", "JPO": "E2",
    "CALL": "CD", "CC": "DC", "CNC": "D4", "CZ": "CC", "CNZ": "C4",
    "CP": "F4", "CM": "FC", "CPE": "EC", "CPO": "E4",
    "RET": "C9", "RC": "D8", "RNC": "D0", "RZ": "C8", "RNZ": "C0",
    "RP": "F0", "RM": "F8", "RPE": "E8", "RPO": "E0",
    "PCHL": "E9",
    "RST 0": "C7", "RST 1": "CF", "RST 2": "D7", "RST 3": "DF",
    "RST 4": "E7", "RST 5": "EF", "RST 6": "F7", "RST 7": "FF",

    // Stack instructions
    "PUSH B": "C5", "PUSH D": "D5", "PUSH H": "E5", "PUSH PSW": "F5",
    "POP B": "C1", "POP D": "D1", "POP H": "E1", "POP PSW": "F1",
    "XTHL": "E3", "SPHL": "F9",

    // I/O instructions
    "IN": "DB", "OUT": "D3",

    // Control instructions
    "NOP": "00", "HLT": "76", "DI": "F3", "EI": "FB",
    "RIM": "20", "SIM": "30"
};

// Instructions that take 8-bit immediate data
const IMMEDIATE_8BIT = ["MVI A", "MVI B", "MVI C", "MVI D", "MVI E", "MVI H", "MVI L", "MVI M",
    "ADI", "ACI", "SUI", "SBI", "ANI", "ORI", "XRI", "CPI", "IN", "OUT"];

// Instructions that take 16-bit address/data
const IMMEDIATE_16BIT = ["LXI B", "LXI D", "LXI H", "LXI SP",
    "LDA", "STA", "LHLD", "SHLD",
    "JMP", "JC", "JNC", "JZ", "JNZ", "JP", "JM", "JPE", "JPO",
    "CALL", "CC", "CNC", "CZ", "CNZ", "CP", "CM", "CPE", "CPO"];



